window.LITERATURE_DATA = {
  "articles": [
    {
      "Priority": "A – Read first",
      "Theme": "Shoulder classification",
      "Year": 2018,
      "First author": "Rivela et al.",
      "Article title": "Analysis and Comparison of Features and Algorithms to Classify Shoulder Movements From sEMG Signals",
      "Evidence type": "Experimental classification",
      "Sensors / methods": "8-channel sEMG; 9 shoulder movements; feature/window/classifier comparison",
      "Why it matters for this project": "Closest methodological match to the project. Supports movement labels, window selection, feature engineering, and classifier choice.",
      "Status": "Peer reviewed",
      "Access": "Open access copy",
      "DOI / article link": "https://doi.org/10.1109/JSEN.2018.2813434",
      "Best review section": "Methods; related work",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "Shoulder classification",
      "Year": 2019,
      "First author": "Amanpreet Kaur",
      "Article title": "Machine learning-based novel approach to classify the shoulder motion of upper limb amputees",
      "Evidence type": "Experimental classification",
      "Sensors / methods": "sEMG; shoulder-motion machine learning in upper-limb amputees",
      "Why it matters for this project": "Direct evidence that shoulder motions can be separated from EMG patterns; useful when discussing generalizability beyond healthy participants.",
      "Status": "Peer reviewed",
      "Access": "PNW access may be needed",
      "DOI / article link": "https://doi.org/10.1016/j.bbe.2019.07.007",
      "Best review section": "Related work; discussion",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "Shoulder classification",
      "Year": 2021,
      "First author": "Tigrini et al.",
      "Article title": "Shoulder Motion Intention Detection Through Myoelectric Pattern Recognition",
      "Evidence type": "Experimental classification",
      "Sensors / methods": "Transient sEMG; time/frequency features; LDA and multinomial logistic regression",
      "Why it matters for this project": "Useful for early movement-intent detection and for comparing time-domain and frequency-domain features.",
      "Status": "Peer reviewed",
      "Access": "Open access copy",
      "DOI / article link": "https://doi.org/10.1109/LSENS.2021.3100607",
      "Best review section": "Methods; related work",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "Shoulder classification",
      "Year": 2023,
      "First author": "Tigrini et al.",
      "Article title": "On the Decoding of Shoulder Joint Intent of Motion From Transient EMG: Feature Evaluation and Classification",
      "Evidence type": "Experimental classification",
      "Sensors / methods": "Transient sEMG; 4 shoulder movements; feature separability and classifier testing",
      "Why it matters for this project": "Very close to the predictive-modeling aim. Helps justify onset-centered windows and feature selection.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1109/TMRB.2023.3320260",
      "Best review section": "Methods; related work",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "Fatigue and dataset",
      "Year": 2024,
      "First author": "Yasar et al.",
      "Article title": "A dataset for fatigue estimation during shoulder internal and external rotation movements using wearables",
      "Evidence type": "Data paper",
      "Sensors / methods": "Wearable sEMG/IMU data; internal and external rotation; graded MVIC fatigue protocol",
      "Why it matters for this project": "Direct match to two project movements and to muscle-fatigue modeling. The public dataset may also help benchmark a pipeline.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1038/s41597-024-03254-8",
      "Best review section": "Methods; fatigue background",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "Signal processing",
      "Year": 2022,
      "First author": "Tanaka et al.",
      "Article title": "Sliding-Window Normalization to Improve the Performance of Machine-Learning Models for Real-Time Motion Prediction Using Electromyography",
      "Evidence type": "Experimental methods",
      "Sensors / methods": "EMG; real-time sliding-window z-score normalization; machine learning",
      "Why it matters for this project": "Directly relevant to the project's sliding-window pipeline and reducing calibration drift.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3390/s22135005",
      "Best review section": "Methods",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "B – Strong support",
      "Theme": "Multimodal fusion",
      "Year": 2019,
      "First author": "Shahzad et al.",
      "Article title": "Enhanced Performance for Multi-Forearm Movement Decoding Using Hybrid IMU–sEMG Interface",
      "Evidence type": "Experimental classification",
      "Sensors / methods": "Hybrid IMU and sEMG; arm-position variation; motion decoding",
      "Why it matters for this project": "Supports fusing muscle and motion signals and explains why IMU data can improve robustness when limb position changes.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3389/fnbot.2019.00043",
      "Best review section": "Methods; discussion",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "B – Strong support",
      "Theme": "Multimodal fusion",
      "Year": 2022,
      "First author": "Xu et al.",
      "Article title": "Gesture recognition using dual-stream CNN based on fusion of sEMG energy kernel phase portrait and IMU amplitude image",
      "Evidence type": "Deep-learning classification",
      "Sensors / methods": "Dual-stream CNN; sEMG and IMU feature-image fusion",
      "Why it matters for this project": "Provides a modern deep-learning fusion architecture to compare with traditional feature-based models.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1016/j.bspc.2021.103364",
      "Best review section": "Related work; future modeling",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "B – Strong support",
      "Theme": "Multimodal fusion",
      "Year": 2022,
      "First author": "Jiang et al.",
      "Article title": "Multi-Category Gesture Recognition Modeling Based on sEMG and IMU Signals",
      "Evidence type": "Experimental classification",
      "Sensors / methods": "sEMG and IMU; multi-category gesture dataset and modeling",
      "Why it matters for this project": "Supports multimodal classification and provides ideas for dataset design, synchronization, and class expansion.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3390/s22155855",
      "Best review section": "Related work; methods",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "B – Strong support",
      "Theme": "IMU classification",
      "Year": 2022,
      "First author": "Cui et al.",
      "Article title": "Recognition of Upper Limb Action Intention Based on IMU",
      "Evidence type": "Experimental classification",
      "Sensors / methods": "IMU angle and angular velocity; upper-limb activity-intention classification",
      "Why it matters for this project": "Shows what IMU-only models can contribute and provides a baseline against which sEMG+IMU fusion can be compared.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3390/s22051954",
      "Best review section": "Related work; baseline",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "IMU shoulder measurement",
      "Year": 2019,
      "First author": "Carnevale et al.",
      "Article title": "Wearable systems for shoulder kinematics assessment: a systematic review",
      "Evidence type": "Systematic review",
      "Sensors / methods": "73 studies of wearable shoulder-kinematics systems",
      "Why it matters for this project": "Strong overview for the background section and for explaining sensor types, placement, clinical use, and limitations.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1186/s12891-019-2930-4",
      "Best review section": "Background; methods",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "IMU validation",
      "Year": 2022,
      "First author": "Henschke et al.",
      "Article title": "Assessing the validity of inertial measurement units for shoulder kinematics using a commercial sensor-software system: A validation study",
      "Evidence type": "Validation study",
      "Sensors / methods": "Commercial IMU system versus optical motion capture during active shoulder movements",
      "Why it matters for this project": "Helps justify IMUs while acknowledging accuracy limits compared with laboratory motion capture.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1002/hsr2.772",
      "Best review section": "Methods; limitations",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "Sensor placement",
      "Year": 2021,
      "First author": "Höglund et al.",
      "Article title": "The importance of inertial measurement unit placement in assessing upper limb motion",
      "Evidence type": "Experimental validation",
      "Sensors / methods": "Different arm and scapular IMU placements across 9 motion tasks",
      "Why it matters for this project": "Directly informs the project's sensor-placement protocol and reproducibility discussion.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1016/j.medengphy.2021.03.010",
      "Best review section": "Methods; limitations",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "B – Strong support",
      "Theme": "IMU processing",
      "Year": 2023,
      "First author": "Fang et al.",
      "Article title": "Conversion of Upper-Limb Inertial Measurement Unit Data to Joint Angles: A Systematic Review",
      "Evidence type": "Systematic review",
      "Sensors / methods": "52 studies; IMU-to-joint-angle methods and accuracy versus optical motion capture",
      "Why it matters for this project": "Useful for explaining coordinate systems, joint-angle estimation, calibration, sensor fusion, and error sources.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3390/s23146535",
      "Best review section": "Methods; limitations",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "sEMG normalization",
      "Year": 2018,
      "First author": "Alenabi et al.",
      "Article title": "Maximal voluntary isometric contraction tests for normalizing electromyographic data from different regions of supraspinatus and infraspinatus muscles: Identifying reliable combinations",
      "Evidence type": "Reliability study",
      "Sensors / methods": "MVIC normalization tests for supraspinatus and infraspinatus regions",
      "Why it matters for this project": "Directly relevant to two target muscles and to selecting defensible EMG normalization procedures.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1016/j.jelekin.2018.04.007",
      "Best review section": "Methods",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "B – Strong support",
      "Theme": "Muscle activation",
      "Year": 2019,
      "First author": "Calver et al.",
      "Article title": "Regional activation of supraspinatus and infraspinatus sub-regions during dynamic tasks performed with free weights",
      "Evidence type": "Experimental biomechanics",
      "Sensors / methods": "Regional EMG of supraspinatus and infraspinatus during dynamic loaded tasks",
      "Why it matters for this project": "Supports muscle-selection rationale and shows that activation varies within rotator-cuff muscle regions.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1016/j.jelekin.2019.05.009",
      "Best review section": "Background; discussion",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "Muscle fatigue",
      "Year": 2022,
      "First author": "Aranha et al.",
      "Article title": "Muscle fatigue response of rotator cuff muscles in different postures",
      "Evidence type": "Experimental biomechanics",
      "Sensors / methods": "EMG fatigue during abduction and external rotation at multiple arm-elevation angles",
      "Why it matters for this project": "Direct match to project movements and fatigue questions; useful for explaining posture-dependent fatigue.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1007/s00402-022-04650-8",
      "Best review section": "Fatigue background; discussion",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "B – Strong support",
      "Theme": "Fatigue and kinematics",
      "Year": 2021,
      "First author": "Dupuis et al.",
      "Article title": "Fatigue, induced via repetitive upper-limb motor tasks, influences trunk and shoulder kinematics during an upper limb reaching task in a virtual reality environment",
      "Evidence type": "Controlled experiment",
      "Sensors / methods": "Repetitive fatigue protocol; reaching at abduction, external rotation, and scaption targets",
      "Why it matters for this project": "Shows that fatigue alters shoulder and trunk kinematics, supporting combined sEMG and IMU measurement.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1371/journal.pone.0249403",
      "Best review section": "Background; discussion",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "B – Strong support",
      "Theme": "Occupational shoulder fatigue",
      "Year": 2022,
      "First author": "De Bock et al.",
      "Article title": "An Occupational Shoulder Exoskeleton Reduces Muscle Activity and Fatigue During Overhead Work",
      "Evidence type": "Randomized crossover experiment",
      "Sensors / methods": "EMG and fatigue outcomes during simulated overhead industrial tasks",
      "Why it matters for this project": "Useful occupational example linking shoulder muscle activity, fatigue, and ergonomic intervention.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1109/TBME.2022.3159094",
      "Best review section": "Discussion; ergonomics",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "sEMG ergonomics",
      "Year": 2021,
      "First author": "Mudiyanselage et al.",
      "Article title": "Automated Workers’ Ergonomic Risk Assessment in Manual Material Handling Using sEMG Wearable Sensors and Machine Learning",
      "Evidence type": "Experimental classification",
      "Sensors / methods": "Wearable sEMG; machine learning; NIOSH lifting-equation risk labels",
      "Why it matters for this project": "The clearest bridge between physiological signals, machine learning, and established ergonomic risk tools.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3390/electronics10202558",
      "Best review section": "Ergonomics; methods",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "Automated RULA/REBA",
      "Year": 2020,
      "First author": "Huang et al.",
      "Article title": "Development and Validation of a Wearable Inertial Sensors-Based Automated System for Assessing Work-Related Musculoskeletal Disorders in the Workspace",
      "Evidence type": "System development and validation",
      "Sensors / methods": "Wearable IMUs; automated RULA, REBA, and biomechanical assessment",
      "Why it matters for this project": "Directly demonstrates how joint kinematics from IMUs can feed standardized ergonomic scores.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3390/ijerph17176050",
      "Best review section": "Ergonomics; methods",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "RULA and IMUs",
      "Year": 2021,
      "First author": "Humadi et al.",
      "Article title": "Instrumented Ergonomic Risk Assessment Using Wearable Inertial Measurement Units: Impact of Joint Angle Convention",
      "Evidence type": "Validation study",
      "Sensors / methods": "IMU versus motion capture; 2D/3D joint angles; RULA scoring",
      "Why it matters for this project": "Important warning that joint-angle conventions can materially change RULA scores and repeatability.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1109/ACCESS.2020.3048645",
      "Best review section": "Ergonomics; limitations",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "B – Strong support",
      "Theme": "Wearable ergonomics",
      "Year": 2021,
      "First author": "Stefana et al.",
      "Article title": "Wearable Devices for Ergonomics: A Systematic Literature Review",
      "Evidence type": "Systematic review",
      "Sensors / methods": "28 studies of wearable devices used for ergonomic purposes",
      "Why it matters for this project": "Broad review for framing how wearables support exposure measurement, feedback, and workplace interventions.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3390/s21030777",
      "Best review section": "Background; ergonomics",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "Wearables and AI ergonomics",
      "Year": 2022,
      "First author": "Donisi et al.",
      "Article title": "Wearable Sensors and Artificial Intelligence for Physical Ergonomics: A Systematic Review of Literature",
      "Evidence type": "Systematic review",
      "Sensors / methods": "Wearable IMU/accelerometer/gyroscope/biopotential sensors combined with AI",
      "Why it matters for this project": "Strong review tying together the project's sensor and predictive-modeling components.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3390/diagnostics12123048",
      "Best review section": "Background; discussion",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "B – Strong support",
      "Theme": "Automated ergonomic scoring",
      "Year": 2022,
      "First author": "Lin et al.",
      "Article title": "Automatic real-time occupational posture evaluation and select corresponding ergonomic assessments",
      "Evidence type": "System development",
      "Sensors / methods": "OpenPose joint angles; automatic selection of RULA, REBA, or OWAS",
      "Why it matters for this project": "Useful comparison to wearable methods and example of integrating multiple ergonomic assessment tools.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1038/s41598-022-05812-9",
      "Best review section": "Ergonomics; related work",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "A – Read first",
      "Theme": "Multi-tool ergonomics",
      "Year": 2024,
      "First author": "Baklouti et al.",
      "Article title": "A Novel IMU-Based System for Work-Related Musculoskeletal Disorders Risk Assessment",
      "Evidence type": "Field system study",
      "Sensors / methods": "IMUs; RULA, REBA, Strain Index, and Rodgers Muscle Fatigue Analysis",
      "Why it matters for this project": "Exactly matches the professor's suggestion to consider RULA, REBA, and other ergonomic tools alongside IMU data.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3390/s24113419",
      "Best review section": "Ergonomics; methods",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "B – Strong support",
      "Theme": "RULA field study",
      "Year": 2024,
      "First author": "Simon et al.",
      "Article title": "Inertial Motion Capturing in Ergonomic Workplace Analysis: Assessing the Correlation between RULA, Upper-Body Posture Deviations and Musculoskeletal Discomfort",
      "Evidence type": "Field study",
      "Sensors / methods": "IMU motion capture; RULA; discomfort questionnaire; production and office workers",
      "Why it matters for this project": "Helps discuss whether RULA scores, measured posture, and actual discomfort tell the same story.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3390/safety10010016",
      "Best review section": "Ergonomics; discussion",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "B – Strong support",
      "Theme": "Ergonomic tool validation",
      "Year": 2024,
      "First author": "Agostinelli et al.",
      "Article title": "Validation of computer vision-based ergonomic risk assessment tools for real manufacturing environments",
      "Evidence type": "Validation study",
      "Sensors / methods": "Computer vision ergonomic scoring in manufacturing environments",
      "Why it matters for this project": "Useful external benchmark for validating an automated assessment system in realistic conditions.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.1038/s41598-024-79373-4",
      "Best review section": "Ergonomics; validation",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "C – Background",
      "Theme": "REBA review",
      "Year": 2020,
      "First author": "Hita-Gutiérrez et al.",
      "Article title": "An Overview of REBA Method Applications in the World",
      "Evidence type": "Review",
      "Sensors / methods": "Review of 91 selected REBA publications",
      "Why it matters for this project": "Provides broad context on where REBA is used and which other methods are commonly paired with it.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3390/ijerph17082635",
      "Best review section": "Background; ergonomics",
      "Reading status": "Not started",
      "Your notes": null
    },
    {
      "Priority": "C – Background",
      "Theme": "RULA review",
      "Year": 2020,
      "First author": "Gómez-Galán et al.",
      "Article title": "Musculoskeletal Risks: RULA Bibliometric Review",
      "Evidence type": "Bibliometric review",
      "Sensors / methods": "Review of 226 RULA publications",
      "Why it matters for this project": "Useful for showing the scope and maturity of RULA research without treating RULA as a physiological measurement.",
      "Status": "Peer reviewed",
      "Access": "Open access",
      "DOI / article link": "https://doi.org/10.3390/ijerph17124354",
      "Best review section": "Background; ergonomics",
      "Reading status": "Not started",
      "Your notes": null
    }
  ],
  "guidance": [
    {
      "Source type": "Foundational paper",
      "Method / topic": "RULA",
      "Author / agency": "McAtamney & Corlett",
      "Year": 1993,
      "Title": "RULA: a survey method for the investigation of work-related upper limb disorders",
      "How to use it": "Original upper-limb posture, force, and muscle-use screening method. Essential even though it is older.",
      "Review status": "Peer reviewed",
      "Link": "https://doi.org/10.1016/0003-6870(93)90080-S"
    },
    {
      "Source type": "Foundational paper",
      "Method / topic": "REBA",
      "Author / agency": "Hignett & McAtamney",
      "Year": 2000,
      "Title": "Rapid entire body assessment (REBA)",
      "How to use it": "Original whole-body observational risk assessment. Use when tasks involve the trunk, legs, load, or unstable postures.",
      "Review status": "Peer reviewed",
      "Link": "https://doi.org/10.1016/S0003-6870(99)00039-3"
    },
    {
      "Source type": "Foundational paper",
      "Method / topic": "Strain Index",
      "Author / agency": "Moore & Garg",
      "Year": 1995,
      "Title": "The Strain Index: A Proposed Method to Analyze Jobs For Risk of Distal Upper Extremity Disorders",
      "How to use it": "Adds intensity, duration, frequency, posture, speed, and task duration; more distal-upper-extremity focused than the NASA shoulder protocol.",
      "Review status": "Peer reviewed",
      "Link": "https://doi.org/10.1080/15428119591016863"
    },
    {
      "Source type": "Foundational paper",
      "Method / topic": "OWAS",
      "Author / agency": "Karhu et al.",
      "Year": 1977,
      "Title": "Correcting working postures in industry: A practical method for analysis",
      "How to use it": "Observational whole-body posture classification; useful as a comparator but less shoulder-specific than RULA.",
      "Review status": "Peer reviewed",
      "Link": "https://doi.org/10.1016/0003-6870(77)90164-8"
    },
    {
      "Source type": "Official guidance",
      "Method / topic": "NIOSH RNLE",
      "Author / agency": "NIOSH",
      "Year": 2021,
      "Title": "Applications Manual for the Revised NIOSH Lifting Equation",
      "How to use it": "Use for manual lifting risk. It does not replace RULA/REBA and may be outside the shoulder-movement protocol unless loads are lifted.",
      "Review status": "Government guidance",
      "Link": "https://www.cdc.gov/niosh/publications/numbered/94-110.html"
    },
    {
      "Source type": "Official guidance",
      "Method / topic": "OSHA ergonomics",
      "Author / agency": "OSHA",
      "Year": 2026,
      "Title": "Ergonomics overview",
      "How to use it": "Official overview explaining ergonomic hazards and work-related musculoskeletal disorders.",
      "Review status": "Government guidance",
      "Link": "https://www.osha.gov/ergonomics"
    },
    {
      "Source type": "Official guidance",
      "Method / topic": "OSHA hazard identification",
      "Author / agency": "OSHA",
      "Year": 2026,
      "Title": "Ergonomics: Identify Problems",
      "How to use it": "Useful for framing risk factors such as posture, repetition, force, and task duration.",
      "Review status": "Government guidance",
      "Link": "https://www.osha.gov/ergonomics/identify-problems"
    },
    {
      "Source type": "Official guidance",
      "Method / topic": "OSHA controls",
      "Author / agency": "OSHA",
      "Year": 2026,
      "Title": "Ergonomics: Solutions to Control Hazards",
      "How to use it": "Use in the discussion section to connect measurement results to practical controls.",
      "Review status": "Government guidance",
      "Link": "https://www.osha.gov/ergonomics/control-hazards"
    },
    {
      "Source type": "Preprint – verify before citing",
      "Method / topic": "Automated RULA pipeline",
      "Author / agency": "González-Alonso et al.",
      "Year": 2026,
      "Title": "Development of an end-to-end hardware and software pipeline for affordable and feasible ergonomics assessment in the automotive industry",
      "How to use it": "Emerging IMU/OpenSim/RULA pipeline with industrial validation. Clearly label as a preprint unless a journal version appears.",
      "Review status": "Preprint",
      "Link": "https://arxiv.org/abs/2601.17574"
    },
    {
      "Source type": "Preprint – verify before citing",
      "Method / topic": "Multimodal RULA",
      "Author / agency": "González-Alonso et al.",
      "Year": 2026,
      "Title": "ME-WARD: A multimodal ergonomic analysis tool for musculoskeletal risk assessment from inertial and video data in working place",
      "How to use it": "Emerging tool that accepts IMU or video joint angles and generates RULA scores. Clearly label as a preprint.",
      "Review status": "Preprint",
      "Link": "https://arxiv.org/abs/2601.17571"
    }
  ]
};

